### ISSUE TITLE
Protocol federation

### ISSUE THREAD

**Issue by ZeLAxyz** [Doccrazy/keycloak-protocol-cas#12]
Hi, thanks for the extension and it helps me a lot. Is it possible to implement a protocol federation mechanism? That is to say after I successfully sso with CAS, I do not need to auth again with OIDC ?

**Comment by Doccrazy** [comment]
I am not aware of any sign-in issues when using multiple protocols. In fact, Keycloak should be handling this implicitly, as you get the same authenticated Keycloak session independent of the SSO protocol used, and should then be automatically signed in with another protocol.

I just tested this with a CAS client and the admin console, and I did not have to sign in twice. Are you sure your OIDC client is not requesting reauthentication with the `prompt` parameter, or the CAS client triggered single-logout, or the session expired in the meantime?

Or maybe I misunderstood your question. It would be great if you could provide more details about your setup.

**Comment by ZeLAxyz** [comment]
Thanks for your kind attention and reply.  You understand my question correctly. I am developing a CAS SSO plugin for Redmine and use Keycloak 4.5.0 as the authentication server.  Currently the plugin is in the development phase.
Some details about my setup is as follows:
1. I setup Keycloak 4.5.0 using almost the defaults, except for turning SSL off and disabling login with email.
2. I use Master realm for my redmine client.
3. For the redmine client, I setup the Client Protocol as CAS, and the Valid Redirect URIs as http://127.0.0.1:3000/login_with_casifier.

The SSO url I access is http://127.0.0.1:8080/auth/realms/master/protocol/cas/login?service=http%3A%2F%2F127.0.0.1%3A3000%2Flogin_with_casifier
 
My test case is 
1. I access the Keycloak admin console and login as admin
2. I input the above URL in the browser window.
3. If everything is alright, Keycloak should redirect me to 127.0.0.1:3000/login_with_casifier. But I got a login windows that require me to authenticate.
4. After I successfully authenticated. I did not need to login again when I try to login to redmine  again.

The reversed process produced the same result. I first login to redmine by CAS, I still need to login admin console with my password and account by OIDC authentication.

Should I test other version of Keycloak and the CAS Plugin?

**Comment by ZeLAxyz** [comment]
[bandicam 2018-11-01 18-55-39-102.zip](https://github.com/Doccrazy/keycloak-protocol-cas/files/2538195/bandicam.2018-11-01.18-55-39-102.zip)
I have made a screencast for this issue. Hope it will help.

**Comment by Doccrazy** [comment]
I was just testing this, and your screencast explains things. Notice how you are logging in to **localhost**:8080/auth, and then redirecting to **127.0.0.1**:8080/auth? Even though they represent the same host, those are two completely different domains with different sets of session cookies.
I am quite certain that when you set redmine to use localhost too, SSO should work as expected.

**Comment by ZeLAxyz** [comment]
You are right. After I set redmine to use localhost, everything just works perfectly! 👍  
Thanks a lot for your great help. I overlooked the browser domain mechnism and have stuck on this for 2 days:)
