### ISSUE TITLE
List on keycloak.org extensions page

### ISSUE THREAD

**Issue by stianst** [Doccrazy/keycloak-protocol-cas#7]
Would be great to see this extension listed on the keycloak.org extensions page. To do that simply send a PR to https://github.com/keycloak/keycloak-web/tree/master/src/main/resources/extensions. You can find a template for the required json file here https://github.com/keycloak/keycloak-web/blob/master/src/main/resources/extension-template.json.

**Comment by Doccrazy** [comment]
Thanks for the suggestion, I didn't know about the extensions page. I submitted a PR at keycloak/keycloak-web#17.
